server:
  port: 8090
spring:
  #activeMQ
  activemq:
    broker-url: tcp://不告诉你:61616
  #配置Redis
  redis:
    host: 不告诉你
    port: 6379
    password: 不告诉你
    database: 0
    #最大空闲连接数
    jedis:
      pool:
        max-idle: 10