server:
  port: 8091

spring:
  dubbo:
    application:
      name: fg-search-service
    server: true
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
  data:
    solr:
      host: http://不告诉你:8088/solr
  activemq:
    broker-url: tcp://不告诉你:61616