server:
  port: 8091

spring:
  dubbo:
    application:
      name: fg-search-service
    server: true
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
  data:
    solr:
      host: http://cloud.dmdream.cn:8088/solr
  activemq:
    broker-url: tcp://193.112.41.124:61616